In [1]:
from src.data_fetcher import DataFetcher, DataFetcherConfig
from src.data_processor import OptionGammaProcessor, OptionGammaConfig
from src.utils import *

In [2]:
cfg = DataFetcherConfig(
        wrds_username="sniperw",
        data_dir="data",
        start_date="2012-01-01",
        end_date="2024-12-31",
        start_year=2012,
        end_year=2024,
        file_type="parquet",
        compression="zstd",
        replace=True,
        crsp_permno_chunk_size=500,
        optionm_secid_chunk_size=5,
        min_abs_prc=None,
        include_ticker_fallback=False,
        keep_intermediate_csv=False,
    )

"""cfg = DataFetcherConfig(
        wrds_username="sniperw",
        data_dir="data",
        start_date="2000-01-01",
        end_date="2025-12-31",
        start_year=2000,
        end_year=2025,
        file_type="parquet",
        compression="zstd",
        replace=False,
        crsp_permno_chunk_size=500,
        optionm_secid_chunk_size=25,
        min_abs_prc=5.0,
        include_ticker_fallback=False,
        keep_intermediate_csv=False,
    )"""
fetcher = DataFetcher(cfg)

In [3]:
fetcher.run_identifier_pipeline()

Loading library list...
Done
quering
query complete
quering
query complete

In [3]:
fetcher.extract_optionm_secnmd()

Loading library list...
Done
quering... start time: 1775150933.113943
query complete, used time: 7.3906285762786865

WindowsPath('data/optionm_secnmd_2012_2024.parquet')

In [2]:
log_parquet_inventory(Path("data"))
log_parquet_inventory(Path("results/option_gamma"))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

WindowsPath('results/option_gamma/parquet_inventory_log.txt')

In [5]:
fetcher.fetch_crsp_dsf(combine_final=True)

quering... start time: 1775150964.709076
query complete, used time: 1.4082603454589844

CRSP DSF month-chunks:   0%|          | 0/2340 [00:00<?, ?chunk/s]

Loading library list...
Loading library list...
Done
Loading library list...
Done
Loading library list...
Done
Done
Loading library list...
Done

Combine CRSP DSF months:   0%|          | 0/156 [00:00<?, ?month/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

WindowsPath('data/crsp_daily_common_2012_2024.parquet')

In [6]:
fetcher.build_crsp_liquidity_panel()

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

WindowsPath('data/crsp_liquidity_panel_2012_2024.parquet')

In [7]:
fetcher.build_top_liquid_stock_universe(top_pct=0.01)

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

WindowsPath('data/crsp_top_liquid_universe_2012_2024.parquet')

In [8]:
fetcher.build_linked_secid_file_from_top_liquid()

WindowsPath('data/linked_secids_top_liquid_2012_2024.parquet')

In [10]:
export_ids_to_txt("data/linked_secids_top_liquid_2012_2024.parquet", "data/secid_list.txt", "secid")

WindowsPath('data/secid_list.txt')

In [ ]:
fetcher.fetch_opprcd()

opprcd month-chunks:   0%|          | 0/1848 [00:00<?, ?task/s]

Loading library list...
Done

In [3]:
fetcher.fetch_secprd()

secprd month-chunks:   0%|          | 0/7332 [00:00<?, ?task/s]

Loading library list...
Loading library list...
Loading library list...
Loading library list...
Loading library list...
Done
Done
Done
Done
Done

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

WindowsPath('data/secprd_linked_2012_2024.parquet')

In [3]:
fetcher.fetch_wrds_signals_raw_plus()

Loading library list...
Done

signals_raw_plus month-chunks:   0%|          | 0/84 [00:00<?, ?task/s]

Loading library list...
Loading library list...
Loading library list...
Loading library list...
Loading library list...
Done
Done
Done
Done
Done

WindowsPath('data/wrds_signals_raw_plus_linked_2018_2024.parquet')

In [5]:
export_parquet_sample_to_csv("data/factors/wrds_signals_raw_plus_linked_2018_2024.parquet", frac=1, order_by="permno")

WindowsPath('data/wrds_signals_raw_plus_linked_2018_2024_sample_100pct.csv')

In [4]:
fetcher.close()

In [5]:
cfg = OptionGammaConfig(
    option_parquet="data/opprcd_linked_2012_2024.parquet",
    spot_parquet="data/secprd_linked_2012_2024.parquet",
    output_dir="results/option_gamma",
    start_date="2012-01-01",
    end_date="2024-12-31",
    secids=None,
    spot_price_field="close",
    require_spot=True,
    memory_limit="32GB",
    threads=8,
)

processor = OptionGammaProcessor(cfg)

[2026-04-03 13:35:23] [INFO] OptionGammaProcessor_1345548111552 - Registering option parquet: data\opprcd_linked_2012_2024.parquet
[2026-04-03 13:35:23] [INFO] OptionGammaProcessor_1345548111552 - Registering spot parquet: data\secprd_linked_2012_2024.parquet

In [3]:
diag = processor.run_diagnostics()
print(diag["spot_join_coverage_report"])

[2026-04-03 13:31:11] [INFO] OptionGammaProcessor_1345548109536 - Query finished in 0.09s

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

[2026-04-03 13:31:15] [INFO] OptionGammaProcessor_1345548109536 - Query finished in 3.79s
[2026-04-03 13:31:15] [INFO] OptionGammaProcessor_1345548109536 - Query finished in 0.15s

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

[2026-04-03 13:31:19] [INFO] OptionGammaProcessor_1345548109536 - Query finished in 3.25s

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

[2026-04-03 13:31:36] [INFO] OptionGammaProcessor_1345548109536 - Query finished in 17.88s
[2026-04-03 13:31:36] [INFO] OptionGammaProcessor_1345548109536 - Query finished in 0.00s
[2026-04-03 13:31:36] [INFO] OptionGammaProcessor_1345548109536 - Query finished in 0.02s

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

[2026-04-03 13:31:42] [INFO] OptionGammaProcessor_1345548109536 - Query finished in 5.30s

   n_option_rows  n_matched_spot  n_missing_spot  matched_ratio
0      302360882     302360462.0           420.0       0.999999

In [6]:
processor.run_baseline_pipeline(
    export_contract_gex="results/option_gamma/contract_gex.parquet",
    export_underlying_daily="results/option_gamma/underlying_gex_daily.parquet",
)

[2026-04-03 13:35:26] [INFO] OptionGammaProcessor_1345548111552 - Exporting query to parquet: results\option_gamma\contract_gex.parquet

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

[2026-04-03 13:37:24] [INFO] OptionGammaProcessor_1345548111552 - Query finished in 117.68s
[2026-04-03 13:37:24] [INFO] OptionGammaProcessor_1345548111552 - Exporting query to parquet: results\option_gamma\underlying_gex_daily.parquet

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

[2026-04-03 13:40:11] [INFO] OptionGammaProcessor_1345548111552 - Query finished in 167.52s

{'contract_gex': WindowsPath('results/option_gamma/contract_gex.parquet'),
 'underlying_daily': WindowsPath('results/option_gamma/underlying_gex_daily.parquet')}

In [7]:
processor.close()

[2026-04-03 13:40:46] [INFO] OptionGammaProcessor_1345548111552 - Closing DuckDB connection

In [9]:
export_parquet_sample_to_csv("results/option_gamma/contract_gex.parquet", n=1000, order_by="date")
export_parquet_sample_to_csv("results/option_gamma/underlying_gex_daily.parquet", frac=1,order_by="date")

WindowsPath('results/option_gamma/underlying_gex_daily_sample_100pct.csv')

In [3]:
out = export_secid_crsp_name_mapping(
    secid_file=r"E:\Pythonfiles\ProjectGamma\data_legacy\linked_secids_top_liquid_2012_2024.parquet",
    stocknames_file=r"E:\Pythonfiles\ProjectGamma\data_legacy\crsp_common_stocknames_2012_2024.parquet",
    output_file=r"E:\Pythonfiles\ProjectGamma\data_legacy\secid_crsp_name_mapping_2012_2024.csv",
    replace=True,
    keep_all_name_rows=False,
)

In [3]:
attach_permno_to_underlying_gex("data/linked_secids_top_liquid_2012_2024.parquet", "results/option_gamma/underlying_gex_daily.parquet", )

Saved merged file to: results\option_gamma\underlying_gex_daily_with_permno.parquet
Rows in underlying file: 574972
Rows with matched permno: 574972 / 574972 (100.00%)
Unique secid in underlying: 231
Unique secid matched: 231

,secid,permno,date,spot,spot_close,spot_return,spot_cfadj,spot_shrout,n_contracts,n_optionids,n_expiries,call_gex_1pct,put_gex_1pct,net_gex_1pct,call_gex_1pt,put_gex_1pt,net_gex_1pt,total_open_interest,total_option_volume
0,100917,21020,2012-01-03,0.286,0.286,-0.182857,2.0,335227.0,131,131,6,1.731392e+04,-1.882287e+04,-1.508957e+03,6.053817e+06,-6.581424e+06,-5.276073e+05,859561.0,10850.0
1,100917,21020,2012-01-04,0.240,0.240,-0.160839,2.0,335227.0,105,105,6,1.467863e+04,-9.765399e+03,4.913226e+03,6.116094e+06,-4.068916e+06,2.047178e+06,673155.0,5328.0
2,100972,20482,2012-01-03,56.720,56.720,0.008714,2.0,1557796.0,145,145,6,6.470252e+07,-1.594878e+07,4.875373e+07,1.140735e+08,-2.811845e+07,8.595510e+07,479966.0,17950.0
3,100972,20482,2012-01-04,56.500,56.500,-0.003879,2.0,1557796.0,136,136,6,6.207143e+07,-1.657594e+07,4.549549e+07,1.098609e+08,-2.933795e+07,8.052300e+07,463190.0,8184.0
4,100972,20482,2012-01-05,56.370,56.370,-0.002301,2.0,1557796.0,153,153,6,6.504547e+07,-1.690875e+07,4.813672e+07,1.153902e+08,-2.999601e+07,8.539422e+07,477457.0,5526.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
574967,219292,24876,2024-12-24,177.410,177.410,0.052191,1.0,175578.0,1246,1246,15,2.691419e+07,-1.663416e+07,1.028003e+07,1.517062e+07,-9.376111e+06,5.794506e+06,339589.0,33720.0
574968,219292,24876,2024-12-26,176.740,176.740,-0.003777,1.0,175578.0,1232,1232,15,3.084575e+07,-1.903855e+07,1.180720e+07,1.745261e+07,-1.077207e+07,6.680546e+06,347943.0,29060.0
574969,219292,24876,2024-12-27,173.540,173.540,-0.018106,1.0,175578.0,1106,1106,15,2.386901e+07,-1.692039e+07,6.948627e+06,1.375419e+07,-9.750136e+06,4.004049e+06,324482.0,18395.0
574970,219292,24876,2024-12-30,165.530,165.530,-0.046156,1.0,175578.0,1235,1235,15,2.366938e+07,-2.063361e+07,3.035766e+06,1.429915e+07,-1.246518e+07,1.833967e+06,349005.0,19315.0
574971,219292,24876,2024-12-31,163.440,163.440,-0.012626,1.0,175578.0,1249,1249,15,2.353979e+07,-2.281773e+07,7.220513e+05,1.440271e+07,-1.396092e+07,4.417837e+05,350954.0,13246.0

In [4]:
extract_crsp_rows_for_linked_permnos("data/linked_secids_top_liquid_2012_2024.parquet", "data/crsp_daily_common_2012_2024.parquet")

Saved filtered CRSP file to: data\crsp_daily_common_2012_2024_linked_permnos.parquet
Input linked permnos: 232
Filtered CRSP rows: 584316
Matched CRSP permnos: 232
Date range: 2012-01-03 to 2024-12-31

,permno,date,prc,ret,retx,shrout,vol,bidlo,askhi
10,10104,2012-01-03,25.86500,0.008382,0.008382,5025837.0,38081439.0,25.83000,26.66000
11,10107,2012-01-03,26.76500,0.031009,0.031009,8390771.0,64904929.0,26.39000,26.96000
15,10147,2012-01-03,21.72000,0.008356,0.008356,2039957.0,27842000.0,21.65000,22.00000
67,10696,2012-01-03,58.56000,-0.003064,-0.003064,140100.0,1195481.0,58.50000,59.97000
94,11081,2012-01-03,14.97500,0.023582,0.023582,1796509.0,13927909.0,14.92000,15.20000
...,...,...,...,...,...,...,...,...,...
12810453,92611,2024-12-31,316.04001,0.002315,0.002315,1729399.0,3963824.0,315.19009,317.66000
12810459,92655,2024-12-31,505.85999,-0.003820,-0.003820,920284.0,4214367.0,503.34000,511.00000
12810484,93002,2024-12-31,231.84000,-0.015876,-0.015876,4686000.0,17778033.0,231.31000,237.46001
12810495,93096,2024-12-31,75.82000,0.001718,0.001718,219926.0,3500350.0,74.92000,76.32500
12810526,93436,2024-12-31,403.84000,-0.032510,-0.032510,3210060.0,76455213.0,402.54001,427.92999

In [3]:
export_ids_to_txt("data/linked_secids_top_liquid_2012_2024.parquet", "data/ticker_list.txt", "ticker")

WindowsPath('data/ticker_list.txt')